name: Verify

on:
  pull_request:
    branches: main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.46.x

      - run: deno fmt --check

      - run: deno lint

      - run: deno test
